sudo: false
dist: trusty

services:
- docker

language: bash

branches:
  only:
  - master

script:
  # Build X86 docker image
  - docker build -f ./x86/Dockerfile -t erikdevries/spotweb .

  # Build ARM docker image
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f ./arm/Dockerfile -t erikdevries/rpi-spotweb .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

    docker tag erikdevries/spotweb erikdevries/spotweb:latest
    docker push erikdevries/spotweb

    docker tag erikdevries/rpi-spotweb erikdevries/rpi-spotweb:latest
    docker push erikdevries/rpi-spotweb
  fi
