#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/app

chown abc:abc /var/run/php

if [ ! -f /config/ownsettings.php ] && [ -f /app/ownsettings.php ]; then
  cp /app/ownsettings.php /config/ownsettings.php
fi

touch /config/ownsettings.php && chown abc:abc /config/ownsettings.php
rm -f /app/ownsettings.php
ln -s /config/ownsettings.php /app/ownsettings.php

if [[ -n "$DB_ENGINE" && -n "$DB_HOST" && -n "$DB_NAME" && -n "$DB_USER" && -n "$DB_PASS" ]]; then
    echo "Creating database configuration"
    echo "<?php" > /config/dbsettings.inc.php
    echo "\$dbsettings['engine'] = '$DB_ENGINE';" >> /config/dbsettings.inc.php
    echo "\$dbsettings['host'] = '$DB_HOST';" >> /config/dbsettings.inc.php
    echo "\$dbsettings['dbname'] = '$DB_NAME';"  >> /config/dbsettings.inc.php
    echo "\$dbsettings['user'] = '$DB_USER';" >> /config/dbsettings.inc.php
    echo "\$dbsettings['pass'] = '$DB_PASS';"  >> /config/dbsettings.inc.php
fi

if [ -f /config/dbsettings.inc.php ]; then
	chown abc:abc /config/dbsettings.inc.php
	rm /app/dbsettings.inc.php
	ln -s /config/dbsettings.inc.php /app/dbsettings.inc.php
else
	echo -e "\nWARNING: You have no database configuration file, either create /config/dbsettings.inc.php or restart this container with the correct environment variables to auto generate the config.\n"
fi


TZ=${TZ:-"America/Edmonton"}
echo -e "Setting (PHP) time zone to ${TZ}\n"
sed -i "s#^;date.timezone =.*#date.timezone = ${TZ}#g"  /etc/php7/php.ini

if [[ -n "$CRON_RETRIEVE" || -n "$CRON_CACHE_CHECK" ]]; then
	if [[ -n "$CRON_RETRIEVE" ]]; then
        echo "$CRON_RETRIEVE s6-setuidgid abc php /app/retrieve.php >/dev/stdout 2>&1" >> /var/spool/cron/crontabs/root
	fi
	if [[ -n "$CRON_CACHE_CHECK" ]]; then
        echo "$CRON_CACHE_CHECK s6-setuidgid abc php /app/bin/check-cache.php >/dev/stdout 2>&1" >> /etc/crontab
	fi
	rm /etc/periodic/hourly/spotweb
fi

